/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BatchActionBar: typeof import('./components/repo/BatchActionBar.vue')['default']
    ChangeTree: typeof import('./components/repo/ChangeTree.vue')['default']
    CommitGraph: typeof import('./components/graph/CommitGraph.vue')['default']
    GroupTree: typeof import('./components/common/GroupTree.vue')['default']
    LogManager: typeof import('./components/common/LogManager.vue')['default']
    RebaseDialog: typeof import('./components/branch/RebaseDialog.vue')['default']
    RepoCard: typeof import('./components/repo/RepoCard.vue')['default']
    RepoTable: typeof import('./components/repo/RepoTable.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    RuntimeErrorAlert: typeof import('./components/runtime/RuntimeErrorAlert.vue')['default']
    SearchBar: typeof import('./components/common/SearchBar.vue')['default']
    SideBySideDiff: typeof import('./components/diff/SideBySideDiff.vue')['default']
    StatusBadge: typeof import('./components/repo/StatusBadge.vue')['default']
    UnifiedDiff: typeof import('./components/diff/UnifiedDiff.vue')['default']
    VirtualList: typeof import('./components/common/VirtualList.vue')['default']
    WorkspaceManager: typeof import('./components/common/WorkspaceManager.vue')['default']
  }
}
